---
# prepare ccnet config
- name:                 generate ccnet config
  become:               yes
  become_user:          '{{ seafile_user }}'
  command:  >
                        {{ SEAFILE_CCNET_INIT }} -c {{ seafile_mylib_dir }}/ccnet --name {{ seafile_user }} --port {{ seafile_ccnet_port }} --host {{ seafile_ip_or_domain }}
                        creates={{ seafile_mylib_dir }}/ccnet/
  environment:          '{{ SEAFILE_ENVIRONMENT }}'

- name:                 register ccnet key ID
  become:               yes
  become_user:          '{{ seafile_user }}'
  shell:                grep ID {{ seafile_mylib_dir }}/ccnet/ccnet.conf | cut -d= -f2
  register:             _seafile_ccnet_ID
  check_mode:           no
  changed_when:         false
  failed_when:          _seafile_ccnet_ID.stdout == "" or _seafile_ccnet_ID.stderr != ""

- name:                 link ccnet peer key
  become:               yes
  become_user:          '{{ seafile_user }}'
  file:
    src:                '{{ seafile_mylib_dir }}/ccnet/mykey.peer'
    dest:               '{{ seafile_ccnet_dir }}/mykey.peer'
    state:              link
    force:              yes
    owner:              '{{ seafile_user }}'
    group:              '{{ seafile_user }}'
    mode:               0640

# prepare seahub_settings secret key
- name:                 generate seahub_settings secret key
  become:               yes
  become_user:          '{{ seafile_user }}'
  shell:  >
                        {{ SEAFILE_SECRET_KEYGEN }} > {{ seafile_mylib_dir }}/seahub_settings_secret_key
                        creates={{ seafile_mylib_dir }}/seahub_settings_secret_key
  environment:          '{{ SEAFILE_ENVIRONMENT }}'

- name:                 register seahub_settings secret key
  become:               yes
  become_user:          '{{ seafile_user }}'
  command:              cat {{ seafile_mylib_dir }}/seahub_settings_secret_key
  register:             _seafile_seahub_settings_secret_key
  check_mode:           no
  changed_when:         false
  failed_when:          _seafile_seahub_settings_secret_key.stdout == "" or _seafile_seahub_settings_secret_key.stderr != ""

